[workspace]
members = [
    "crates/core",
    "crates/lockfile",
    "crates/rundir",
    "crates/test",
    "crates/winmutex",
]
resolver = "3"

[package]
name = "daemonbit"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description.workspace = true
documentation.workspace = true
readme.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
daemonbit-core = { workspace = true }

[target.'cfg(unix)'.dependencies]
daemonbit-lockfile = { workspace = true }

[target.'cfg(windows)'.dependencies]
daemonbit-winmutex = { workspace = true }

[workspace.package]
version = "0.1.1"
authors = ["Kamil Becmer"]
edition = "2024"
rust-version = "1.85.0"
description = "Cross-platform daemon lifecycle primitives"
documentation = "https://docs.rs/daemonbit"
readme = "README.md"
repository = "https://github.com/becmer/daemonbit"
license = "MIT OR Apache-2.0"
keywords = ["daemon", "service", "systemd", "scm", "cross-platform"]
categories = ["api-bindings", "asynchronous", "concurrency", "filesystem", "os"]

[workspace.dependencies]
daemonbit-core = { path = "crates/core", version = "0.1.1" }
daemonbit-lockfile = { path = "crates/lockfile", version = "0.1.1" }
daemonbit-rundir = { path = "crates/rundir", version = "0.1.1" }
daemonbit-test = { path = "crates/test", version = "0.1.1" }
daemonbit-winmutex = { path = "crates/winmutex", version = "0.1.1" }

claims = "0.8"
const_env = "0.1"
memchr = "2"
ntest = "0.9"
parking_lot = "0.12"
tracing = "0.1"
tracing-subscriber = "0.3"
